version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: reservation-postgres
    environment:
      POSTGRES_DB: reservationdb
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - reservation-net

volumes:
  postgres_data:

networks:
  reservation-net:
    driver: bridge